[project]
name = "portfolio-website"
version = "0.1.0"
description = "Portfolio website."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.2",
    "python-dotenv>=1.0.1",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.7.0",
    "uv>=0.4.24",
]
